export type ColumnDataType = "text" | "serial" | "timestamp";

interface ColumnBuilderState<TName extends string> {
  readonly name: TName;
  readonly dataType: ColumnDataType;
  readonly isPrimaryKey: boolean;
  readonly isNotNull: boolean;
  readonly hasDefault: boolean;
}

/**
 * A single column definition. `$selectType`/`$insertType` are phantom —
 * never assigned at runtime, read only via `typeof col.$selectType` in type
 * position. `TName` carries the declared column name (the string passed to
 * `text()`/`serial()`/`timestamp()`) as a literal type — this is what lets
 * `InferRawTable` (table.ts) key Kysely's `Database` type by the real
 * declared column name instead of whatever object key it happens to be
 * assigned to in a `columns` record.
 */
export class ColumnBuilder<TName extends string, TSelect, TInsert> {
  readonly name: TName;
  readonly dataType: ColumnDataType;
  readonly isPrimaryKey: boolean;
  readonly isNotNull: boolean;
  readonly hasDefault: boolean;

  declare readonly $selectType: TSelect;
  declare readonly $insertType: TInsert;

  constructor(state: ColumnBuilderState<TName>) {
    this.name = state.name;
    this.dataType = state.dataType;
    this.isPrimaryKey = state.isPrimaryKey;
    this.isNotNull = state.isNotNull;
    this.hasDefault = state.hasDefault;
  }

  /** Narrows both select and insert types by excluding `null`. */
  notNull(): ColumnBuilder<TName, Exclude<TSelect, null>, Exclude<TInsert, null>> {
    return new ColumnBuilder({ ...this.state(), isNotNull: true }) as ColumnBuilder<
      TName,
      Exclude<TSelect, null>,
      Exclude<TInsert, null>
    >;
  }

  /** Primary keys are DB-generated by default, so insert becomes optional. */
  primaryKey(): ColumnBuilder<TName, TSelect, TInsert | undefined> {
    return new ColumnBuilder({
      ...this.state(),
      isPrimaryKey: true,
      isNotNull: true,
      hasDefault: true,
    }) as ColumnBuilder<TName, TSelect, TInsert | undefined>;
  }

  defaultNow(): ColumnBuilder<TName, TSelect, TInsert | undefined> {
    return new ColumnBuilder({ ...this.state(), hasDefault: true }) as ColumnBuilder<
      TName,
      TSelect,
      TInsert | undefined
    >;
  }

  private state(): ColumnBuilderState<TName> {
    return {
      name: this.name,
      dataType: this.dataType,
      isPrimaryKey: this.isPrimaryKey,
      isNotNull: this.isNotNull,
      hasDefault: this.hasDefault,
    };
  }
}

export function text<TName extends string>(
  name: TName,
): ColumnBuilder<TName, string | null, string | null> {
  return new ColumnBuilder({
    name,
    dataType: "text",
    isPrimaryKey: false,
    isNotNull: false,
    hasDefault: false,
  });
}

export function serial<TName extends string>(
  name: TName,
): ColumnBuilder<TName, number, number | undefined> {
  return new ColumnBuilder({
    name,
    dataType: "serial",
    isPrimaryKey: false,
    isNotNull: true,
    hasDefault: true,
  }) as ColumnBuilder<TName, number, number | undefined>;
}

export function timestamp<TName extends string>(
  name: TName,
): ColumnBuilder<TName, Date | null, Date | null> {
  return new ColumnBuilder({
    name,
    dataType: "timestamp",
    isPrimaryKey: false,
    isNotNull: false,
    hasDefault: false,
  });
}
