export type ColumnDataType = "text" | "serial" | "timestamp";

interface ColumnBuilderState {
  readonly name: string;
  readonly dataType: ColumnDataType;
  readonly isPrimaryKey: boolean;
  readonly isNotNull: boolean;
  readonly hasDefault: boolean;
}

/**
 * A single column definition. `$selectType`/`$insertType` are phantom —
 * never assigned at runtime, read only via `typeof col.$selectType` in type position.
 */
export class ColumnBuilder<TSelect, TInsert> {
  readonly name: string;
  readonly dataType: ColumnDataType;
  readonly isPrimaryKey: boolean;
  readonly isNotNull: boolean;
  readonly hasDefault: boolean;

  declare readonly $selectType: TSelect;
  declare readonly $insertType: TInsert;

  constructor(state: ColumnBuilderState) {
    this.name = state.name;
    this.dataType = state.dataType;
    this.isPrimaryKey = state.isPrimaryKey;
    this.isNotNull = state.isNotNull;
    this.hasDefault = state.hasDefault;
  }

  /** Narrows both select and insert types by excluding `null`. */
  notNull(): ColumnBuilder<Exclude<TSelect, null>, Exclude<TInsert, null>> {
    return new ColumnBuilder({ ...this.state(), isNotNull: true }) as ColumnBuilder<
      Exclude<TSelect, null>,
      Exclude<TInsert, null>
    >;
  }

  /** Primary keys are DB-generated by default, so insert becomes optional. */
  primaryKey(): ColumnBuilder<TSelect, TInsert | undefined> {
    return new ColumnBuilder({
      ...this.state(),
      isPrimaryKey: true,
      isNotNull: true,
      hasDefault: true,
    }) as ColumnBuilder<TSelect, TInsert | undefined>;
  }

  defaultNow(): ColumnBuilder<TSelect, TInsert | undefined> {
    return new ColumnBuilder({ ...this.state(), hasDefault: true }) as ColumnBuilder<
      TSelect,
      TInsert | undefined
    >;
  }

  private state(): ColumnBuilderState {
    return {
      name: this.name,
      dataType: this.dataType,
      isPrimaryKey: this.isPrimaryKey,
      isNotNull: this.isNotNull,
      hasDefault: this.hasDefault,
    };
  }
}

export function text(name: string): ColumnBuilder<string | null, string | null> {
  return new ColumnBuilder({
    name,
    dataType: "text",
    isPrimaryKey: false,
    isNotNull: false,
    hasDefault: false,
  });
}

export function serial(name: string): ColumnBuilder<number, number | undefined> {
  return new ColumnBuilder({
    name,
    dataType: "serial",
    isPrimaryKey: false,
    isNotNull: true,
    hasDefault: true,
  }) as ColumnBuilder<number, number | undefined>;
}

export function timestamp(name: string): ColumnBuilder<Date | null, Date | null> {
  return new ColumnBuilder({
    name,
    dataType: "timestamp",
    isPrimaryKey: false,
    isNotNull: false,
    hasDefault: false,
  });
}
